---
title: "tables_figures"
output:
  pdf_document:
    keep_tex: true
  word_document: default
editor_options:
  chunk_output_type: inline
---

```{r,include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, warning=FALSE, message=FALSE)
library(fossil)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(dplyr)
library(kableExtra)
tmp_path <- '~/Documents/PACS sim/'
```

## Simulation study

### Sample size 1e5

$\beta_0 = (1,1,1,0,0,0,0,0,0.5,0.2)$

```{r,include=FALSE}
# Simulation study 1

n_sim <- 1000

# Case 1

case_id = 'Res1e5'

beta0 = c(1,1,1,0,0,0,0,0,0.5,0)

# MSE metric

mse_mat <- rep(NA, length = 9)

names(mse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8')

# Model selection accuracy

sparse_mat <- rep(NA, length = 10)

names(sparse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sparsity <- function(x, theta0) {
  x <- round(x, 3)
  (theta0 == 0 & x == 0) | (theta0 > 0 & x > 0) | (theta0 < 0 & x < 0)
}

sensitivity_mat <- rep(NA, length = 10)

names(sensitivity_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sensitivity <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 > 0 & x > 0 | theta0 < 0 & x < 0)/(sum(theta0!=0))
}

false_positive_mat <- rep(NA, length = 10)

names(false_positive_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

false_positive <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 == 0 & x != 0)/sum(theta0 == 0)
}

beta_true <- beta0

beta_true <- matrix(rep(beta_true,n_sim),nrow = n_sim,byrow = TRUE)  

m <- 1

ivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_res <- rbind(ivw_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW'] <- median(apply(ivw_res - beta_true,1,function(x) sum(x^2)))

ivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_inclusion <- rbind(ivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_ivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

srivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_res <- rbind(srivw_res, read.csv(paste0(tmp_path,case_id, "/res_srivw_",i,".csv")))
    },error = function(e) {})
}

srivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_inclusion <- rbind(srivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_srivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

mse_mat['SRIVW'] <- median(apply(srivw_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

ivw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_lasso_res <- rbind(ivw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_lasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

# MVMR-dLASSO

divw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    divw_lasso_res <- rbind(divw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_dlasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['dIVW-LASSO'] <- median(apply(divw_lasso_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-PACS

pacs_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_res <- rbind(pacs_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS'] <- median(apply(pacs_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_pacs <- rbind(cluster_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

# MVMR-PACS-0.8

pacs_0.8_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_0.8_res <- rbind(pacs_0.8_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS-0.8'] <- median(apply(pacs_0.8_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_0.8_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_0.8_pacs <- rbind(cluster_0.8_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_0.8_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_0.8_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_0.8_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

mrbma_res <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_res <- rbind(mrbma_res, read.csv(paste0(tmp_path,case_id, "/res_mrbma_",i,".csv")))
    },error = function(e) {})
}

mse_mat['MRBMA-0.5'] <- median(apply(mrbma_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

mrbma_mip <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_mip <- rbind(mrbma_mip, read.csv(paste0(tmp_path,case_id, "/mrbma_mip_",i,".csv")))
    },error = function(e) {})
}

# change threshold

mrbma_thres <- 0.2

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.5

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.8

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-cML-SuSiE
susie_res <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_res <- rbind(susie_res, read.csv(paste0(tmp_path,case_id, "/res_susie_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

susie_num_cluster <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_num_cluster <- rbind(susie_num_cluster, read.csv(paste0(tmp_path,case_id, "/susie_num_cluster_",i,".csv")))
    },error = function(e) {})
}

table(susie_num_cluster)
```

```{r}
iv_strength <- NULL

for (i in 1:1000) {
        tryCatch({
        iv_strength <- rbind(iv_strength, read.csv(paste0(tmp_path,case_id, "/res_iv_strength_",i,".csv")))
        },error = function(e) {})
}

summary(iv_strength)

conditional_F <- NULL

for (i in 1:1000) {
        tryCatch({
        conditional_F <- rbind(conditional_F, read.csv(paste0(tmp_path,case_id, "/res_cond_F_",i,".csv")))
        },error = function(e) {})
}

summary(conditional_F)
```

```{r}
mse_1e5 <- print(round(mse_mat,3))
mse_1e5['MVMR-cML-SuSiE'] <- NA
correct_sparsity_1e5 <- print(round(sparse_mat,3))
sensitivity_1e5 <- print(round(sensitivity_mat,3))
false_positive_1e5 <- print(round(false_positive_mat,3))
```

```{r,fig.width=18,fig.height=6}
ivw_res_to_plot <- ivw_res
srivw_res_to_plot <- srivw_res
ivw_lasso_res_to_plot <- ivw_lasso_res
dlasso_to_plot <- divw_lasso_res
pacs_to_plot <- pacs_res
mrbma_to_plot <- mrbma_res

ivw_res_to_plot$Estimator <- 'MVMR-IVW'
srivw_res_to_plot$Estimator <- 'SRIVW'
ivw_lasso_res_to_plot$Estimator <- 'MVMR-Lasso'
dlasso_to_plot$Estimator <- 'MVMR-dLasso'
pacs_to_plot$Estimator <- 'MVMR-PACS'
mrbma_to_plot$Estimator <- 'MR-BMA'

# Combine data frames into one
df <- bind_rows(ivw_res_to_plot, 
                srivw_res_to_plot,
                ivw_lasso_res_to_plot, 
                dlasso_to_plot,
                pacs_to_plot,
                mrbma_to_plot)

# Convert to long format
df_long <- df %>%
  pivot_longer(cols = starts_with("V"), names_to = "Parameter", values_to = "Value")

df_long$Parameter <- factor(df_long$Parameter, paste0("V",1:10), labels = paste0("RF",1:10))

# Create the grouped boxplot
df_long <- df_long %>%
  mutate(Value = pmax(pmin(Value, 3), -3))  # Restrict values within [-2, 2]

df_long$Estimator <- factor(df_long$Estimator, c('MVMR-IVW','SRIVW','MVMR-Lasso','MVMR-dLasso','MVMR-PACS','MR-BMA'))

p1 <- ggplot(df_long, aes(x = Parameter, y = Value, fill = Estimator)) +
  geom_boxplot(outlier.alpha = 0.5,  # Make outliers slightly transparent
               outlier.shape = 16,   # Keep default point shape for outliers
               outlier.size = 1.5,   # Adjust outlier size
               width = 0.4) +  # Omit outliers for clarity
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 12),
    panel.grid.major = element_line(size = 0.5, linetype = 'dotted', color = "gray")
  ) +
  scale_y_continuous(breaks = -3:3) + 
  scale_fill_brewer(palette = "Set2") + # Use colorblind-friendly palette
  labs(x = "Risk Factor", y = "Estimates", fill = "Estimator",
       title = "Sample size N = 1e4. Average IV strength parameter = -0.1.")
```

### Sample size 2e5

```{r,include=FALSE}
# Simulation study 1

n_sim <- 1000

# Case 1

case_id = 'Res2e5'

beta0 = c(1,1,1,0,0,0,0,0,0.5,0)

# MSE metric

mse_mat <- rep(NA, length = 9)

names(mse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8')

# Model selection accuracy

sparse_mat <- rep(NA, length = 10)

names(sparse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sparsity <- function(x, theta0) {
  x <- round(x, 3)
  (theta0 == 0 & x == 0) | (theta0 > 0 & x > 0) | (theta0 < 0 & x < 0)
}

sensitivity_mat <- rep(NA, length = 10)

names(sensitivity_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sensitivity <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 > 0 & x > 0 | theta0 < 0 & x < 0)/(sum(theta0!=0))
}

false_positive_mat <- rep(NA, length = 10)

names(false_positive_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

false_positive <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 == 0 & x != 0)/sum(theta0 == 0)
}

beta_true <- beta0

beta_true <- matrix(rep(beta_true,n_sim),nrow = n_sim,byrow = TRUE)  

m <- 1

ivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_res <- rbind(ivw_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW'] <- median(apply(ivw_res - beta_true,1,function(x) sum(x^2)))

ivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_inclusion <- rbind(ivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_ivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

srivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_res <- rbind(srivw_res, read.csv(paste0(tmp_path,case_id, "/res_srivw_",i,".csv")))
    },error = function(e) {})
}

srivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_inclusion <- rbind(srivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_srivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

mse_mat['SRIVW'] <- median(apply(srivw_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

ivw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_lasso_res <- rbind(ivw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_lasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

# MVMR-dLASSO

divw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    divw_lasso_res <- rbind(divw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_dlasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['dIVW-LASSO'] <- median(apply(divw_lasso_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-PACS

pacs_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_res <- rbind(pacs_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS'] <- median(apply(pacs_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_pacs <- rbind(cluster_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

# MVMR-PACS-0.8

pacs_0.8_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_0.8_res <- rbind(pacs_0.8_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS-0.8'] <- median(apply(pacs_0.8_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_0.8_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_0.8_pacs <- rbind(cluster_0.8_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_0.8_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_0.8_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_0.8_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

mrbma_res <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_res <- rbind(mrbma_res, read.csv(paste0(tmp_path,case_id, "/res_mrbma_",i,".csv")))
    },error = function(e) {})
}

mse_mat['MRBMA-0.5'] <- median(apply(mrbma_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

mrbma_mip <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_mip <- rbind(mrbma_mip, read.csv(paste0(tmp_path,case_id, "/mrbma_mip_",i,".csv")))
    },error = function(e) {})
}

# change threshold

mrbma_thres <- 0.2

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.5

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.8

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-cML-SuSiE
susie_res <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_res <- rbind(susie_res, read.csv(paste0(tmp_path,case_id, "/res_susie_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

susie_num_cluster <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_num_cluster <- rbind(susie_num_cluster, read.csv(paste0(tmp_path,case_id, "/susie_num_cluster_",i,".csv")))
    },error = function(e) {})
}

table(susie_num_cluster)
```

```{r}
iv_strength <- NULL

for (i in 1:1000) {
        tryCatch({
        iv_strength <- rbind(iv_strength, read.csv(paste0(tmp_path,case_id, "/res_iv_strength_",i,".csv")))
        },error = function(e) {})
}

summary(iv_strength)

conditional_F <- NULL

for (i in 1:1000) {
        tryCatch({
        conditional_F <- rbind(conditional_F, read.csv(paste0(tmp_path,case_id, "/res_cond_F_",i,".csv")))
        },error = function(e) {})
}

summary(conditional_F)
```

```{r}
mse_2e5 <- print(round(mse_mat,3))
mse_2e5['MVMR-cML-SuSiE'] <- NA
correct_sparsity_2e5 <- print(round(sparse_mat,3))
sensitivity_2e5 <- print(round(sensitivity_mat,3))
false_positive_2e5 <- print(round(false_positive_mat,3))
```

```{r,fig.width=18,fig.height=6}
ivw_res_to_plot <- ivw_res
srivw_res_to_plot <- srivw_res
ivw_lasso_res_to_plot <- ivw_lasso_res
dlasso_to_plot <- divw_lasso_res
pacs_to_plot <- pacs_res
mrbma_to_plot <- mrbma_res

ivw_res_to_plot$Estimator <- 'MVMR-IVW'
srivw_res_to_plot$Estimator <- 'SRIVW'
ivw_lasso_res_to_plot$Estimator <- 'MVMR-Lasso'
dlasso_to_plot$Estimator <- 'MVMR-dLasso'
pacs_to_plot$Estimator <- 'MVMR-PACS'
mrbma_to_plot$Estimator <- 'MR-BMA'

# Combine data frames into one
df <- bind_rows(ivw_res_to_plot, 
                srivw_res_to_plot,
                ivw_lasso_res_to_plot, 
                dlasso_to_plot,
                pacs_to_plot,
                mrbma_to_plot)

# Convert to long format
df_long <- df %>%
  pivot_longer(cols = starts_with("V"), names_to = "Parameter", values_to = "Value")

df_long$Parameter <- factor(df_long$Parameter, paste0("V",1:10), labels = paste0("RF",1:10))

# Create the grouped boxplot
df_long <- df_long %>%
  mutate(Value = pmax(pmin(Value, 3), -3))  # Restrict values within [-2, 2]

df_long$Estimator <- factor(df_long$Estimator, c('MVMR-IVW','SRIVW','MVMR-Lasso','MVMR-dLasso','MVMR-PACS','MR-BMA'))

p2 <- ggplot(df_long, aes(x = Parameter, y = Value, fill = Estimator)) +
  geom_boxplot(outlier.alpha = 0.5,  # Make outliers slightly transparent
               outlier.shape = 16,   # Keep default point shape for outliers
               outlier.size = 1.5,   # Adjust outlier size
               width = 0.4) +  # Omit outliers for clarity
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 12),
    panel.grid.major = element_line(size = 0.5, linetype = 'dotted', color = "gray")
  ) +
  scale_y_continuous(breaks = -3:3) + 
  scale_fill_brewer(palette = "Set2") + # Use colorblind-friendly palette
  labs(x = "Risk Factor", y = "Estimates", fill = "Estimator",
       title = "Sample size N = 2e5. Average IV strength parameter = 1.9.")
```

### Sample size 3e5

```{r,include=FALSE}
# Simulation study 1

n_sim <- 1000

# Case 1

case_id = 'Res3e5'

beta0 = c(1,1,1,0,0,0,0,0,0.5,0)

# MSE metric

mse_mat <- rep(NA, length = 9)

names(mse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8')

# Model selection accuracy

sparse_mat <- rep(NA, length = 10)

names(sparse_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sparsity <- function(x, theta0) {
  x <- round(x, 3)
  (theta0 == 0 & x == 0) | (theta0 > 0 & x > 0) | (theta0 < 0 & x < 0)
}

sensitivity_mat <- rep(NA, length = 10)

names(sensitivity_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

sensitivity <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 > 0 & x > 0 | theta0 < 0 & x < 0)/(sum(theta0!=0))
}

false_positive_mat <- rep(NA, length = 10)

names(false_positive_mat) <- c('IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')

false_positive <- function(x, theta0) {
  x <- round(x, 3)
  sum(theta0 == 0 & x != 0)/sum(theta0 == 0)
}

beta_true <- beta0

beta_true <- matrix(rep(beta_true,n_sim),nrow = n_sim,byrow = TRUE)  

m <- 1

ivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_res <- rbind(ivw_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW'] <- median(apply(ivw_res - beta_true,1,function(x) sum(x^2)))

ivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_inclusion <- rbind(ivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_ivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW'] <- mean(apply(ivw_inclusion * ivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

srivw_res <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_res <- rbind(srivw_res, read.csv(paste0(tmp_path,case_id, "/res_srivw_",i,".csv")))
    },error = function(e) {})
}

srivw_inclusion <- NULL

for (i in 1:1000) {
    tryCatch({
    srivw_inclusion <- rbind(srivw_inclusion, read.csv(paste0(tmp_path,case_id, "/res_srivw_inclusion_",i,".csv")))
    },error = function(e) {})
}

mse_mat['SRIVW'] <- median(apply(srivw_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['SRIVW'] <- mean(apply(srivw_inclusion * srivw_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

ivw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    ivw_lasso_res <- rbind(ivw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_ivw_lasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res - beta_true,1,function(x) sum(x^2)))

sparse_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}))

sensitivity_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}))

false_positive_mat['IVW-LASSO'] <- mean(apply(ivw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}))

# MVMR-dLASSO

divw_lasso_res <- NULL

for (i in 1:1000) {
    tryCatch({
    divw_lasso_res <- rbind(divw_lasso_res, read.csv(paste0(tmp_path,case_id, "/res_dlasso_",i,".csv")))
    },error = function(e) {})
}

mse_mat['dIVW-LASSO'] <- median(apply(divw_lasso_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['dIVW-LASSO'] <- mean(apply(divw_lasso_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-PACS

pacs_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_res <- rbind(pacs_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS'] <- median(apply(pacs_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS'] <- mean(apply(pacs_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_pacs <- rbind(cluster_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_v2_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

# MVMR-PACS-0.8

pacs_0.8_res <- NULL

for (i in 1:1000) {
    tryCatch({
    pacs_0.8_res <- rbind(pacs_0.8_res, read.csv(paste0(tmp_path,case_id, "/res_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mse_mat['PACS-0.8'] <- median(apply(pacs_0.8_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

sparse_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['PACS-0.8'] <- mean(apply(pacs_0.8_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

cluster_0.8_pacs <- NULL

for (i in 1:1000) {
    tryCatch({
    cluster_0.8_pacs <- rbind(cluster_0.8_pacs, read.csv(paste0(tmp_path,case_id, "/cluster_pacs_0.8_",i,".csv")))
    },error = function(e) {})
}

mean(apply(cluster_0.8_pacs, 1, function(x) {rand.index(x, c(1,1,1,2,2,2,2,2,3,4))}),na.rm = TRUE)

mean(apply(cluster_0.8_pacs[,1:3], 1, function(x) {all(x==x[1])}))

cluster.hist <- apply(cluster_0.8_pacs,1,function(x) paste0(x,collapse = '-'))

table(cluster.hist)

mrbma_res <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_res <- rbind(mrbma_res, read.csv(paste0(tmp_path,case_id, "/res_mrbma_",i,".csv")))
    },error = function(e) {})
}

mse_mat['MRBMA-0.5'] <- median(apply(mrbma_res - beta_true,1,function(x) sum(x^2)),na.rm = TRUE)

mrbma_mip <- NULL

for (i in 1:1000) {
    tryCatch({
    mrbma_mip <- rbind(mrbma_mip, read.csv(paste0(tmp_path,case_id, "/mrbma_mip_",i,".csv")))
    },error = function(e) {})
}

# change threshold

mrbma_thres <- 0.2

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.2'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.5

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.5'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

mrbma_thres <- 0.8

mrmba_inclusion <- mrbma_mip >= mrbma_thres

sparse_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['MRBMA-0.8'] <- mean(apply(mrmba_inclusion * mrbma_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

# MVMR-cML-SuSiE
susie_res <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_res <- rbind(susie_res, read.csv(paste0(tmp_path,case_id, "/res_susie_",i,".csv")))
    },error = function(e) {})
}

sparse_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sparsity(x, beta_true[1,]))}),na.rm = TRUE)

sensitivity_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(sensitivity(x, beta_true[1,]))}),na.rm = TRUE)

false_positive_mat['SuSiE'] <- mean(apply(susie_res, 1, function(x) {mean(false_positive(x, beta_true[1,]))}),na.rm = TRUE)

susie_num_cluster <- NULL

for (i in 1:1000) {
    tryCatch({
    susie_num_cluster <- rbind(susie_num_cluster, read.csv(paste0(tmp_path,case_id, "/susie_num_cluster_",i,".csv")))
    },error = function(e) {})
}

table(susie_num_cluster)
```

```{r}
iv_strength <- NULL

for (i in 1:1000) {
        tryCatch({
        iv_strength <- rbind(iv_strength, read.csv(paste0(tmp_path,case_id, "/res_iv_strength_",i,".csv")))
        },error = function(e) {})
}

summary(iv_strength)

conditional_F <- NULL

for (i in 1:1000) {
        tryCatch({
        conditional_F <- rbind(conditional_F, read.csv(paste0(tmp_path,case_id, "/res_cond_F_",i,".csv")))
        },error = function(e) {})
}

summary(conditional_F)
```

```{r}
mse_3e5 <- print(round(mse_mat,3))
mse_3e5['MVMR-cML-SuSiE'] <- NA
correct_sparsity_3e5 <- print(round(sparse_mat,3))
sensitivity_3e5 <- print(round(sensitivity_mat,3))
false_positive_3e5 <- print(round(false_positive_mat,3))
```

```{r,fig.width=18,fig.height=6}
ivw_res_to_plot <- ivw_res
srivw_res_to_plot <- srivw_res
ivw_lasso_res_to_plot <- ivw_lasso_res
dlasso_to_plot <- divw_lasso_res
pacs_to_plot <- pacs_res
mrbma_to_plot <- mrbma_res

ivw_res_to_plot$Estimator <- 'MVMR-IVW'
srivw_res_to_plot$Estimator <- 'SRIVW'
ivw_lasso_res_to_plot$Estimator <- 'MVMR-Lasso'
dlasso_to_plot$Estimator <- 'MVMR-dLasso'
pacs_to_plot$Estimator <- 'MVMR-PACS'
mrbma_to_plot$Estimator <- 'MR-BMA'

# Combine data frames into one
df <- bind_rows(ivw_res_to_plot, 
                srivw_res_to_plot,
                ivw_lasso_res_to_plot, 
                dlasso_to_plot,
                pacs_to_plot,
                mrbma_to_plot)

# Convert to long format
df_long <- df %>%
  pivot_longer(cols = starts_with("V"), names_to = "Parameter", values_to = "Value")

df_long$Parameter <- factor(df_long$Parameter, paste0("V",1:10), labels = paste0("RF",1:10))

# Create the grouped boxplot
df_long <- df_long %>%
  mutate(Value = pmax(pmin(Value, 3), -3))  # Restrict values within [-2, 2]

df_long$Estimator <- factor(df_long$Estimator, c('MVMR-IVW','SRIVW','MVMR-Lasso','MVMR-dLasso','MVMR-PACS','MR-BMA'))

p3 <- ggplot(df_long, aes(x = Parameter, y = Value, fill = Estimator)) +
  geom_boxplot(outlier.alpha = 0.5,  # Make outliers slightly transparent
               outlier.shape = 16,   # Keep default point shape for outliers
               outlier.size = 1.5,   # Adjust outlier size
               width = 0.4) +  # Omit outliers for clarity
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    legend.title = element_text(size = 12),
    panel.grid.major = element_line(size = 0.5, linetype = 'dotted', color = "gray")
  ) +
  scale_y_continuous(breaks = -3:3) + 
  scale_fill_brewer(palette = "Set2") + # Use colorblind-friendly palette
  labs(x = "Risk Factor", y = "Estimates", fill = "Estimator",
       title = "Sample size N = 3e5. Average IV strength parameter = 4.0.")
```


```{r,fig.width=18,fig.height=18}
library(ggpubr)
jpeg("supp_main_sim_boxplot.jpeg",width = 81000,height = 8000,res= 600)
ggarrange(p1,p2,p3,ncol = 1, common.legend = TRUE)
dev.off()
```

```{r,include = TRUE}
Estimator <- c('MVMR-IVW','SRIVW','IVW-LASSO','dIVW-LASSO','PACS','PACS-0.8','MRBMA-0.2','MRBMA-0.5','MRBMA-0.8','SuSiE')
tbl <- cbind(Estimator,mse_1e5,mse_2e5,mse_3e5,correct_sparsity_1e5,correct_sparsity_2e5,correct_sparsity_3e5,sensitivity_1e5,sensitivity_2e5,sensitivity_3e5,false_positive_1e5,false_positive_2e5,false_positive_3e5)
kable(tbl,format = 'latex',align = 'c',vline = '',row.names = FALSE,col.names = c('Estimator',rep(c('N=1e5','N=2e5','N=3e5'),4)),booktabs = TRUE, caption = paste0('Simulation results. 1000 runs.'), linesep = '') %>%
  add_header_above(c(' ' = 1,'MSE' = 3, 'Model Identification' = 3, 'Sensitivity' = 3, 'False Positive' = 3)) %>%
  collapse_rows(columns = 1) %>%
  kable_styling(latex_options = c('HOLD_position','scale_down'))
```